# Generated by Django 2.1.4 on 2018-12-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20181227_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='작성일',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='내용',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='내용2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='게시일',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='제목',
            new_name='title',
        ),
    ]
